export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_USERS_ALL_SETTLED_SUCCESS    = 'LOAD_USERS_ALL_SETTLED_SUCCESS';
export const LOAD_USERS_ALL_UNSETTLED_SUCCESS  = 'LOAD_USERS_ALL_UNSETTLED_SUCCESS';
